services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

  app:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80:8000
    restart: always
    volumes:
      - ./apps:/app
    command: /bin/sh run.sh
    env_file:
      - .env
